const gamesList = [
  { id: 1, name: "Football", icon: "⚽" },
  { id: 2, name: "Cricket", icon: "🏏" },
  { id: 3, name: "Box Cricket", icon: "🏏" },
  { id: 4, name: "Badminton", icon: "🏸" },
  { id: 5, name: "Tennis", icon: "🎾" },
  { id: 6, name: "Basketball", icon: "🏀" },
  { id: 7, name: "Volleyball", icon: "🏐" },
  { id: 8, name: "Kabaddi", icon: "🏃" },
  { id: 9, name: "Hockey", icon: "🏑" },
  { id: 10, name: "Table Tennis", icon: "🏓" },
  { id: 11, name: "Futsal", icon: "⚽" },
  { id: 12, name: "Skating", icon: "⛸️" },
  { id: 13, name: "Swimming", icon: "🏊" },
  { id: 14, name: "Pickleball", icon: "🎾" },
  { id: 15, name: "Baseball", icon: "⚾" },
  { id: 16, name: "Rugby", icon: "🏈" },
  { id: 17, name: "Handball", icon: "🤾" },
  { id: 18, name: "Squash", icon: "🎾" },
  { id: 19, name: "Kho Kho", icon: "🏃" },
  { id: 20, name: "Archery", icon: "🏹" },
  { id: 21, name: "Athletics", icon: "🏃" },
  { id: 22, name: "Go Karting", icon: "🏎️" },
  { id: 23, name: "Teqball", icon: "⚽" },
  { id: 24, name: "Chess", icon: "♟️" },
  { id: 25, name: "Paintball", icon: "🎯" },
  { id: 26, name: "Dodgeball", icon: "🏐" },
  { id: 27, name: "Bowling", icon: "🎳" },
  { id: 28, name: "Golf", icon: "⛳" },
  { id: 29, name: "Pool", icon: "🎱" },
  { id: 30, name: "Snooker", icon: "🎱" },
  { id: 31, name: "Shooting", icon: "🎯" },
  { id: 32, name: "Bungee Jumping", icon: "🪂" },
  { id: 33, name: "Paragliding", icon: "🪂" },
  { id: 34, name: "Skydiving", icon: "🪂" },
  { id: 35, name: "Surfing", icon: "🏄" },
  { id: 36, name: "Wrestling", icon: "🤼" },
  { id: 37, name: "Martial Arts", icon: "🥋" },
  { id: 38, name: "Skateboarding", icon: "🛹" },
];

export default gamesList;
